version: "3"
services:
  postgres_test:
    image: 'postgres:latest'
    ports:
      - '5434:5432'
  postgres:
    image: 'postgres:latest'
    ports:
      - '5433:5432'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./API
    volumes:
      - ./API:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=job_board_dev
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./Client
    volumes:
      - /app/node_modules
      - ./Client:/app
